nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset:
        cutout:
          - dataset: /pscratch/sd/t/timothys/nested-eagle/v0/data/hrrr.analysis.zarr
            trim_edge: [15, 16, 15, 16]
          - dataset: /pscratch/sd/t/timothys/nested-eagle/v0/data/gfs.analysis.zarr
        adjust: all
        min_distance_km: 0
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights
        norm: unit-max
        fill_value: 0
      cutout_mask:
        _target_: anemoi.graphs.nodes.attributes.CutOutMask
  hidden:
    node_builder:
      _target_: anemoi.graphs.nodes.NPZFileNodes
      npz_file: "latentx2.combined.npz"
      lat_key: lat
      lon_key: lon

edges:
# Encoder
- source_name: data
  target_name: hidden
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 14
    source_mask_attr_name: null
    target_mask_attr_name: null
#  - _target_: anemoi.graphs.edges.CutOffEdges
#    cutoff_factor: 0.6
#    source_mask_attr_name: null
#    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std
# Decoder
- source_name: hidden
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 3
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

post_processors: []
# I don't fully understand this option b/c it doesn't solve my problem
#- _target_: anemoi.graphs.processors.RemoveUnconnectedNodes
#  nodes_name: data
