nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset: /pscratch/sd/t/timothys/anemoi-house/gfs/0.25-degree/data/gfs.zarr
    attributes:
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights
        norm: unit-max
        fill_value: 0
  hidden_1:
    node_builder:
      _target_: anemoi.graphs.nodes.NPZFileNodes
      npz_file: "latent.stage1.global_quarter_degree.sorted.npz"
      lat_key: lat
      lon_key: lon
  hidden_2:
    node_builder:
      _target_: anemoi.graphs.nodes.NPZFileNodes
      npz_file: "latent.stage2.global_quarter_degree.sorted.npz"
      lat_key: lat
      lon_key: lon

edges:
# Encoder 1
- source_name: data
  target_name: hidden_1
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 4
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

# Encoder 2
- source_name: hidden_1
  target_name: hidden_2
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 4
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

# Decoder 1
- source_name: hidden_2
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 3
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

## Decoder 2
#- source_name: hidden_1
#  target_name: data
#  edge_builders:
#  - _target_: anemoi.graphs.edges.KNNEdges
#    num_nearest_neighbours: 3
#    source_mask_attr_name: null
#    target_mask_attr_name: null
#  attributes:
#    edge_length:
#      _target_: anemoi.graphs.edges.attributes.EdgeLength
#      norm: unit-max
#    edge_dirs:
#      _target_: anemoi.graphs.edges.attributes.EdgeDirection
#      norm: unit-std

post_processors: []
