asynchronous: True # Whether to plot asynchronously
datashader: True # With 1 degree data, this one point per data looks ridiculous
frequency: # Frequency of the plotting
  batch: 750
  epoch: 5

# Parameters to plot
parameters:
- geopotential_500
- temperature_850
- u_component_of_wind_850
- v_component_of_wind_850
- 2m_temperature
- 10m_u_component_of_wind
- 10m_v_component_of_wind
- surface_pressure
- total_precipitation_6hr

# Sample index
sample_idx: 0

# Precipitation and related fields
precip_and_related_fields: [total_precipitation_6hr]

# select colormaps
colormaps:
  default:
    _target_: anemoi.training.utils.custom_colormaps.MatplotlibColormap
    name: viridis
  # in order to use distinctipy, you need to install the package
  # default:
  #   _target_: anemoi.training.utils.custom_colormaps.DistinctipyColormap
  #   n_colors: 8
  error:
    _target_: anemoi.training.utils.custom_colormaps.MatplotlibColormap
    name: bwr
  precip:
    _target_: anemoi.training.utils.custom_colormaps.MatplotlibColormapClevels
    clevels: ["#ffffff", "#04e9e7", "#019ff4", "#0300f4", "#02fd02", "#01c501", "#008e00", "#fdf802", "#e5bc00", "#fd9500", "#fd0000", "#d40000", "#bc0000", "#f800fd"]
    variables: ${diagnostics.plot.precip_and_related_fields}

callbacks:
  # Add plot callbacks here
  - _target_: anemoi.training.diagnostics.callbacks.plot.GraphTrainableFeaturesPlot
    every_n_epochs: 5
  - _target_: anemoi.training.diagnostics.callbacks.plot.PlotLoss
    # group parameters by categories when visualizing contributions to the loss
    # one-parameter groups are possible to highlight individual parameters
    parameter_groups:
      moisture: [total_precipitation_6hr]
      sfc_wind: [10m_u_component_of_wind, 10m_v_component_of_wind]
    every_n_batches: ${diagnostics.plot.frequency.batch}
  - _target_: anemoi.training.diagnostics.callbacks.plot.PlotSample
    sample_idx: ${diagnostics.plot.sample_idx}
    per_sample : 6
    parameters: ${diagnostics.plot.parameters}
    every_n_batches: ${diagnostics.plot.frequency.batch}
    #Defining the accumulation levels for precipitation related fields and the colormap
    accumulation_levels_plot: [0, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 100] # in mm
    precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
    colormaps: ${diagnostics.plot.colormaps}


  - _target_: anemoi.training.diagnostics.callbacks.plot.PlotSpectrum
    # every_n_batches: 100 # Override for batch frequency
    # min_delta: 0.01 # Minimum distance between two consecutive points
    sample_idx: ${diagnostics.plot.sample_idx}
    every_n_batches: ${diagnostics.plot.frequency.batch}
    parameters:
      - geopotential_500
      - total_precipitation_6hr
      - 2m_temperature
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
  - _target_: anemoi.training.diagnostics.callbacks.plot.PlotHistogram
    sample_idx: ${diagnostics.plot.sample_idx}
    every_n_batches: ${diagnostics.plot.frequency.batch}
    precip_and_related_fields: ${diagnostics.plot.precip_and_related_fields}
    parameters:
      - geopotential_500
      - total_precipitation_6hr
      - 2m_temperature
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
