name: eagle
channels:
  - conda-forge
  - default
dependencies:
  - python=3.12
  - ufs2arco=0.19.0
  - pip
  - pip:
    - anemoi-datasets==0.5.28
    - anemoi-graphs==0.8.4
    - anemoi-inference==0.9.0
    - anemoi-models==0.12.0
    - anemoi-training==0.9.0
    - anemoi-transform==0.1.19
    - anemoi-utils==0.4.40
    - eagle-tools==0.17.1
    - mlflow-skinny==2.22.4
    - torch==2.6.0
    - torchvision==0.21.0
    - xmovie @ git+https://github.com/timothyas/xmovie.git@21f4c541ba46b88bb14e98c52f1d57f0d61c0508
