nodes:
  data:
    node_builder:
      _target_: anemoi.graphs.nodes.AnemoiDatasetNodes
      dataset:
        cutout:
          - dataset: /pscratch/sd/t/timothys/nested-eagle/0.25deg-06km/data/hrrr.zarr
            trim_edge: [25, 24, 25, 26]
          - dataset: /pscratch/sd/t/timothys/nested-eagle/0.25deg-06km/data/gfs.zarr
        adjust: all
        min_distance_km: 6
    attributes:
      cutout_mask:
        _target_: anemoi.graphs.nodes.attributes.CutOutMask
      boundary_mask:
        _target_: anemoi.graphs.nodes.attributes.BooleanNot
        masks:
          _target_: anemoi.graphs.nodes.attributes.CutOutMask
      area_weight:
        _target_: anemoi.graphs.nodes.attributes.SphericalAreaWeights
        norm: unit-max
        fill_value: 0
      lam_area_weight:
        _target_: anemoi.graphs.nodes.attributes.MaskedPlanarAreaWeights
        mask_node_attr_name: cutout_mask
        norm: unit-max
  hidden_1:
    node_builder:
      _target_: anemoi.graphs.nodes.NPZFileNodes
      npz_file: "latentx2.stage1.spongex1.combined.sorted.npz"
      lat_key: lat
      lon_key: lon
  hidden_2:
    node_builder:
      _target_: anemoi.graphs.nodes.NPZFileNodes
      npz_file: "latentx4.stage2.spongex1.combined.sorted.npz"
      lat_key: lat
      lon_key: lon

edges:
# Encoder 1
- source_name: data
  target_name: hidden_1
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 12
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

# Encoder 2
- source_name: hidden_1
  target_name: hidden_2
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 12
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

# Decoder
- source_name: hidden_2
  target_name: data
  edge_builders:
  - _target_: anemoi.graphs.edges.KNNEdges
    num_nearest_neighbours: 3
    source_mask_attr_name: null
    target_mask_attr_name: null
  attributes:
    edge_length:
      _target_: anemoi.graphs.edges.attributes.EdgeLength
      norm: unit-max
    edge_dirs:
      _target_: anemoi.graphs.edges.attributes.EdgeDirection
      norm: unit-std

post_processors: []
